name: primeira-pipeline
on:
  push:
    branches: ["develop"]
  workflow_dispatch:
jobs:
  primeiro-job: 
    name: "Meu primeiro job"
    runs-on: ubuntu-latest
    steps:
     - name: "Minha primeira ação"
       run: echo "Hello World"
     - name: "Segunda ação"
       run: |
         echo "Você criou o seu primeiro workflow!!"
         echo "Parabéns"
  segundo-job:
    name: "Instalação do ambiente nodejs"
    runs-on: ubuntu-latest
    steps:
      - name: "Verificação da versão do current nodejs."
        run: node --version
      - name: "Definição da versão do nodejs"
      - uses: actions/setup-node@v4
        with: 
          node-version: '20.13.1'
      - name: "Verificação da versão do depois de instalar nodejs."
        run: node --version
          
